/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.scalien.keyspace;

public class imaxdiv_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected imaxdiv_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(imaxdiv_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      keyspace_clientJNI.delete_imaxdiv_t(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setQuot(long value) {
    keyspace_clientJNI.imaxdiv_t_quot_set(swigCPtr, this, value);
  }

  public long getQuot() {
    return keyspace_clientJNI.imaxdiv_t_quot_get(swigCPtr, this);
  }

  public void setRem(long value) {
    keyspace_clientJNI.imaxdiv_t_rem_set(swigCPtr, this, value);
  }

  public long getRem() {
    return keyspace_clientJNI.imaxdiv_t_rem_get(swigCPtr, this);
  }

  public imaxdiv_t() {
    this(keyspace_clientJNI.new_imaxdiv_t(), true);
  }

}
