/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.scalien.keyspace;

class keyspace_clientJNI {
  public final static native void imaxdiv_t_quot_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_quot_get(long jarg1, imaxdiv_t jarg1_);
  public final static native void imaxdiv_t_rem_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_rem_get(long jarg1, imaxdiv_t jarg1_);
  public final static native long new_imaxdiv_t();
  public final static native void delete_imaxdiv_t(long jarg1);
  public final static native long imaxabs(long jarg1);
  public final static native long imaxdiv(long jarg1, long jarg2);
  public final static native long strtoimax(String jarg1, long jarg2, int jarg3);
  public final static native java.math.BigInteger strtoumax(String jarg1, long jarg2, int jarg3);
  public final static native long new_Keyspace_NodeParams(int jarg1);
  public final static native void delete_Keyspace_NodeParams(long jarg1);
  public final static native void Keyspace_NodeParams_Close(long jarg1, Keyspace_NodeParams jarg1_);
  public final static native void Keyspace_NodeParams_AddNode(long jarg1, Keyspace_NodeParams jarg1_, String jarg2);
  public final static native void Keyspace_NodeParams_nodec_set(long jarg1, Keyspace_NodeParams jarg1_, int jarg2);
  public final static native int Keyspace_NodeParams_nodec_get(long jarg1, Keyspace_NodeParams jarg1_);
  public final static native void Keyspace_NodeParams_nodes_set(long jarg1, Keyspace_NodeParams jarg1_, long jarg2);
  public final static native long Keyspace_NodeParams_nodes_get(long jarg1, Keyspace_NodeParams jarg1_);
  public final static native void Keyspace_NodeParams_num_set(long jarg1, Keyspace_NodeParams jarg1_, int jarg2);
  public final static native int Keyspace_NodeParams_num_get(long jarg1, Keyspace_NodeParams jarg1_);
  public final static native void Keyspace_ResultBegin(long jarg1);
  public final static native void Keyspace_ResultNext(long jarg1);
  public final static native boolean Keyspace_ResultIsEnd(long jarg1);
  public final static native void Keyspace_ResultClose(long jarg1);
  public final static native String Keyspace_ResultKey(long jarg1);
  public final static native String Keyspace_ResultValue(long jarg1);
  public final static native int Keyspace_ResultTransportStatus(long jarg1);
  public final static native int Keyspace_ResultConnectivityStatus(long jarg1);
  public final static native int Keyspace_ResultTimeoutStatus(long jarg1);
  public final static native int Keyspace_ResultCommandStatus(long jarg1);
  public final static native long Keyspace_Create();
  public final static native int Keyspace_Init(long jarg1, long jarg2, Keyspace_NodeParams jarg2_);
  public final static native void Keyspace_Destroy(long jarg1);
  public final static native long Keyspace_GetResult(long jarg1);
  public final static native void Keyspace_SetGlobalTimeout(long jarg1, java.math.BigInteger jarg2);
  public final static native void Keyspace_SetMasterTimeout(long jarg1, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger Keyspace_GetGlobalTimeout(long jarg1);
  public final static native java.math.BigInteger Keyspace_GetMasterTimeout(long jarg1);
  public final static native int Keyspace_GetMaster(long jarg1);
  public final static native void Keyspace_DistributeDirty(long jarg1, boolean jarg2);
  public final static native int Keyspace_Get(long jarg1, String jarg2);
  public final static native int Keyspace_DirtyGet(long jarg1, String jarg2);
  public final static native int Keyspace_Count(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_CountStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyCount(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyCountStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_ListKeys(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_ListKeysStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyListKeys(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyListKeysStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_ListKeyValues(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_ListKeyValuesStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyListKeyValues(long jarg1, String jarg2, String jarg3, java.math.BigInteger jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_DirtyListKeyValuesStr(long jarg1, String jarg2, String jarg3, String jarg4, boolean jarg5, boolean jarg6);
  public final static native int Keyspace_Set(long jarg1, String jarg2, String jarg3);
  public final static native int Keyspace_TestAndSet(long jarg1, String jarg2, String jarg3, String jarg4);
  public final static native int Keyspace_Add(long jarg1, String jarg2, long jarg3);
  public final static native int Keyspace_AddStr(long jarg1, String jarg2, String jarg3);
  public final static native int Keyspace_Delete(long jarg1, String jarg2);
  public final static native int Keyspace_Remove(long jarg1, String jarg2);
  public final static native int Keyspace_Rename(long jarg1, String jarg2, String jarg3);
  public final static native int Keyspace_Prune(long jarg1, String jarg2);
  public final static native int Keyspace_SetExpiry(long jarg1, String jarg2, int jarg3);
  public final static native int Keyspace_RemoveExpiry(long jarg1, String jarg2);
  public final static native int Keyspace_ClearExpiries(long jarg1);
  public final static native int Keyspace_Begin(long jarg1);
  public final static native int Keyspace_Submit(long jarg1);
  public final static native int Keyspace_Cancel(long jarg1);
  public final static native boolean Keyspace_IsBatched(long jarg1);
  public final static native void Keyspace_SetTrace(boolean jarg1);
}
