CLIENTLIB_OBJECTS = \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceClient.o \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceClientConn.o \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceCommand.o \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceResponse.o \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceResult.o \
	$(BUILD_DIR)/Application/Keyspace/Client/keyspace_client.o \
	$(BUILD_DIR)/System/Common.o \
	$(BUILD_DIR)/System/Config.o \
	$(BUILD_DIR)/System/Log.o \
	$(BUILD_DIR)/System/Platform.o \
	$(BUILD_DIR)/System/Time_Posix.o \
	$(BUILD_DIR)/System/Events/EventLoop.o \
	$(BUILD_DIR)/System/Events/Scheduler.o \
	$(BUILD_DIR)/System/IO/Endpoint.o \
	$(BUILD_DIR)/System/IO/Socket_Posix.o \
	$(BUILD_DIR)/System/IO/IOProcessor_$(PLATFORM).o \

SWIG_LIB_OBJECT = \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceClientWrap.o

PYTHON_CLIENT_OBJECT = \
	$(BUILD_DIR)/Application/Keyspace/Client/Python/keyspace_client_python.o
