#!/bin/sh

PORT=22222
if [ "$3" != "" ]; then
	PORT=$3
fi

SERVER_CONSOLE=localhost
if [ "$2" != "" ]; then
	SERVER_CONSOLE=$2
fi

echo_sleep() {
	echo $1
	sleep $2
}

echo_sleep "$1" 1 | telnet $SERVER_CONSOLE $PORT
