#! /bin/sh
#
# keyspace: Scalien Keyspace replicated key-value database

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Keyspace"
RUNSAFE="yes"
DEFAULT=/etc/default/keyspace

if [ `id -u` != "0" ]
then
  echo "You must be root to start this appication."
  exit 1
fi

test -f $DEFAULT || exit 0
. $DEFAULT

test -x $DAEMON || exit 0

pidof_daemon() {
        pid=`ps auxw | grep "$DAEMON" | grep -v grep | awk '{print $2}'`
}

case "$1" in
  start)
	echo -n "Starting $DESC: "

	$SAFE_DAEMON $DEFAULT_CONFIG $DATABASE_DIR
	
	if [ $? -eq 0 ]; then
		echo "$NAME."
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	pidof_daemon
    if [ "$pid" != "" ]; then
    	kill $pid
		pidof_daemon
		if [ "$pid" != "" ]; then
			sleep 1
			kill -9 $pid
			pidof_daemon
			if [ "$pid" != "" ]; then
				echo "$NAME ($pid) could not be stopped!"
				exit 1
			fi
		fi
		echo "$NAME."
	else
		echo "$NAME is not running."
    fi
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
