#!/bin/sh

safe_keyspace()
{
	while (:); do
		$1 $2 &> /dev/null
		EXITSTATUS=$?
		#echo "keyspace exited with $EXITSTATUS"
		if [ "$EXITSTATUS" = "0" -o "$EXITSTATUS" = "1" -o "$EXITSTATUS" = "143" ]; then
			exit 0
		fi
		if [ "$EXITSTATUS" = "2" ]; then
			# delete database files
			$KEYSPACE_DIR=`dirname $2`
			rm $KEYSPACE_DIR/__*
			rm $KEYSPACE_DIR/log*
			rm $KEYSPACE_DIR/keyspace
		fi
	done
}

safe_keyspace $1 $2 &
