#!/bin/sh

safe_keyspace()
{
	while (:); do
		$1 $2 2>&1 >> /dev/null
		EXITSTATUS=$?
		if [ "$EXITSTATUS" = "0" -o "$EXITSTATUS" = "1" -o "$EXITSTATUS" = "143" ]; then
			exit 0
		fi
		if [ "$EXITSTATUS" = "2" ]; then
			# delete database files
			KEYSPACE_DIR=$3
			if [ "$KEYSPACE_DIR" = "" ]; then
				KEYSPACE_DIR=`dirname $1`
			fi
			rm $KEYSPACE_DIR/__*
			rm $KEYSPACE_DIR/log*
			rm $KEYSPACE_DIR/keyspace
		fi
	done
}

safe_keyspace $1 $2 $3 2>&1 >> /dev/null &
