#ifndef KEYSPACECONSTS_H
#define KEYSPACECONSTS_H

#define KEYSPACE_KEY_SIZE		(1*KB)
#define KEYSPACE_VAL_SIZE		(1*MB)

#define BUF_SIZE				(KEYSPACE_KEY_SIZE + KEYSPACE_VAL_SIZE + 1*KB)

#define CATCHUP_PORT_OFFSET		2

#endif
